services:
    www:
        image: manologcode/flask_tasks
        build:
            context: .
            dockerfile: Dockerfile
        container_name: flask_tasks
        # command: /usr/local/bin/gunicorn entrypoint:app  -w 5 --worker-class=gevent --worker-connections=1000 -b :5000 --reload
        command: python -m flask --debug run --host=0.0.0.0 --reload
        ports: 
            - "5000:5000"
        volumes:
            - ./app:/app
        environment:
            - FLASK_APP=app:create_app('development')
            - FLASK_ENV=development
            - DATABASE_URL=mysql://root:toor@mariadb/development
            - DATABASE_URL_DEV=mysql://root:toor@mariadb/development
            - SECRET_KEY=mysecretkey
        links:
            - mariadb
        networks:
            - default
    mariadb:
        image: mariadb:10.3
        container_name: mariadb_tasks
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: 'development'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: '1234'
            MYSQL_ROOT_PASSWORD: toor 
        volumes:
            #- ./_inimysql:/docker-entrypoint-initdb.d
            - mariadb_tasks:/var/lib/mysql
        networks:
            - default 

    phpmyadmin:
        container_name: phpmyadmin
        depends_on:
            - mariadb
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: toor 
            UPLOAD_LIMIT: 20000K
        networks:
            - default 

volumes:
    mariadb_tasks: